#!/bin/bash

# Ensure you're running the proper runtime when you switch branches

function update_platform() {
    echo "Updating dependencies to match requirements of commit (add .bin/ to the start of your PATH for this to work)"

    state exec exit 0

}

if [ "$3" == "1" ]; then
    update_platform
fi
